### ISSUE TITLE
bug: events do not working

### ISSUE THREAD

**Issue by expcapitaldev** [trustly/cordova-plugin-trustly-checkout#1]
on Android "handleTrustlyEvent" and iOS do not work events ABORT and I think other 

 pls describe how work you SDK with next situation:
1. I open url
2. click close
3. I see url redirected to my server endpoint
4. for example my server endpoint will be send 401 status , if we try to open this endpoint into browser
5. I did not see any events from your SDK
6. showTrustlyCheckout promise without then/catch block finished

**Comment by Macksen** [comment]
Hi @expcapitaldev, if I am understanding this correctly, you're aborting an order and then expecting to receive an ABORT event but you're not actually receiving this event?

**Comment by expcapitaldev** [comment]
@Macksen  Hi, yes, I am aborting an order and then expecting to receive an ABORT event but I am not actually receiving this event

**Comment by Macksen** [comment]
How are these methods implemented on your side? Does the SDK work other than that, as in, it opens a webview correctly?

**Comment by expcapitaldev** [comment]
@Macksen webview opens correctly, I can create build with our SDK and send for testing/debugging
and I used next:
https://github.com/trustly/cordova-plugin-trustly-checkout#usage

**Comment by Macksen** [comment]
I created a test app and implemented the SDK functionality like so: 

```

function onDeviceReady() {
  trustly
    .showTrustlyCheckout(
      "<YOUR-TRUSTLY-CHECKOUT-URL>"
    )
    .then((successUrl) => {
    })
    .catch((err) => {
      alert(JSON.stringify(err));
    });
}
```

and was able to receive the event. 

Can I see your implementation of this?
Did you install the SDK through the CLI? `cordova plugin add https://github.com/trustly/cordova-plugin-trustly-checkout`

**Comment by expcapitaldev** [comment]
@Macksen  thank you, I implemented plugin using `cordova prepare` and `cordova build` but no difference.
I will recheck, I think issue from my side

**Comment by expcapitaldev** [comment]
@Macksen so, my issue, thank you a lot, issue will be closed
